name: 'publish-helm-chart'
description: 'publish helm chart to ACR'
inputs:
  azure-credentials:  
    description: 'A azure credentials to login to azure'
    required: true    
  chart-path: 
    description: 'the path to the helm chart, ".helm/<my-chart>"'
    required: true
  helm-registry-url: 
    description: 'the full url to the acr'
    required: true
  helm-registry-username:
    description: 'the username to authenticate to the external registry'
    required: true
  helm-registry-password:
    description: 'the password to authenticate to the external registry'
    required: true


runs:
  using: "composite"
  steps:    
    - name: registry
      shell: bash
      run: |
         export HELM_EXPERIMENTAL_OCI=1
         helm registry login ${{ helm-registry-url }}  --username ${{ inputs.helm-registry-username }}   --password ${{ inputs.helm-registry-passwords }}
    - name: publish
      shell: bash
      run: |
          export HELM_EXPERIMENTAL_OCI=1
          helm package ${{inputs.chart-path}}
          helm push *.tgz oci://${{ steps.GetSecrets.outputs.acr-server-url }}/helm

    
    
